In [1]:
color = ('red', 'orange', 'green')

In [2]:
print(color.count('orange'))

1

In [3]:
print(color.index('orange'))

1

In [4]:
color[1]= 'black'

TypeError: 'tuple' object does not support item assignment

In [5]:
colors = ['red', 'orange', 'green']

In [7]:
colors[1] = 'black'

In [8]:
colors

['red', 'black', 'green']

In [9]:
for color in color:
    print (color)

red
orange
green

In [23]:
for color in colors:
    print(color)

red
black
green

In [24]:
color

'green'

In [1]:
a = {
    'a' : 20,
    'b' : 'z',
    'c' : 7
}

In [26]:
for key, value in a.items():
    print (key, value)

a 20
b z
c 7

In [27]:
items(help)

NameError: name 'items' is not defined

In [4]:
15%3

0

In [24]:
a = 4
row= a
col= a
matrix = []

for i in range(row):                         # Outer loop: runs 4 times (i = 0, 1, 2, 3)
    row = []                                 # Creates a NEW empty list for each iteration
    for c in range(col):                     # Inner loop: runs 4 times (c = 0, 1, 2, 3)
        row.append(0)                        # Adds 0 to the current row
    matrix.append(row)                       # Adds the completed row to the matrix

for row in matrix:                           # map(function, iterable) applies a function to every item in the iterable.
    print (' '.join(map(str, row)))
    #     └─┬─┘ └────┬────┘  └┬┘
    #       │        │        └─ the list of numbers
    #       │        └─ convert each to string
    #       └─ glue with spaces between

0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0

In [19]:
matrix = [[0 for _ in range(4)] for _ in range(4)]   
for row in matrix:
    print (' '.join(map(str, row))) #same code as above 
#row = [0, 0, 0, 0]
      #   ↓
    #map(str, row)
     #    ↓
    #['0', '0', '0', '0']   ← all strings now
   #      ↓
#' '.join(...)
  #       ↓
 #  '0 0 0 0'              ← single string with spaces //
    # JOin only works with strings thats why first need to convert to string

0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0

In [29]:
for level in range(1, row + 1):
    print (' '*(row - level) + '*' * (2 * level-1))

NameError: name 'row' is not defined

In [11]:
row=5
for level in range(1, row + 1):
    print(' ' * (row - level) + '*' * (2 * level - 1))

    *
   ***
  *****
 *******
*********

In [25]:
i = 1
while i < 5:
    print (i)
    i += 1

1
2
3
4

In [27]:
for i in range(2):
    print ('outer ')
    for j in range(3):
        print ('    inner')

outer
    inner
    inner
    inner
outer
    inner
    inner
    inner

In [28]:
for char in 'python':
    print (char)

p
y
t
h
o
n

In [29]:
# Looping over Data Structure - Strings
count = 0
for char in 'banana':
    if char == 'a':
        count += 1
print (count)

3

In [12]:
s ='python'
rev=''
for ch in s:
    rev=ch+rev
print (rev)

nohtyp

In [6]:
 # Dictionaries - Looping
a = {
    'a' : 20,
    'b' : 'z',
    'c' : 7
}
for key in a:
    print(key)

a
b
c

In [32]:
for key in a:
    print(a[key])

20
z
7

In [33]:
for key in a:
    print (key,':', a[key])

a : 20
b : z
c : 7

In [37]:
for key,values in a.items():
    print(key,':',values)

a : 20
b : z
c : 7

In [25]:
studentList = [
    { 'name': ' Ali',
      'age':22,
      'grade':'A' },
    {'name': 'Sara',
     'age':17,
     'grade':'B' }
]
for student in studentList:
    print(f"Name: {student.get('name')}|Grade: {student.get('grade')}")

Name:  Ali|Grade: A
Name: Sara|Grade: B

In [53]:
def greet():
    print('Hello world')
greet()
greet('Ali')

Hello world

TypeError: greet() takes 0 positional arguments but 1 was given

In [58]:
def greet(name):
    print('Hello ', name)
greet('Ali')

Hello  Ali

In [59]:
def add(a,b):
    return a+b
add(3,5)

8

In [60]:
result = add(3,6)
print (result)

9

In [9]:
def square (num):
    return num*num
result= square(6)
result

36

In [10]:
print(square(5))

25

In [13]:
def show():
    x=5
    print(x)

In [66]:
x=10
show()
print(x)

5
10

### Lambda- Fuction

In [67]:
add = lambda a,b: a+b
print (add(4,6))

10

In [68]:
doubleIt = lambda n: n*2
print (doubleIt(3))

6

In [28]:
nums = [1,2,3,4]
square=list(map(lambda x: x*x, nums))

In [29]:
print (square)

[1, 4, 9, 16]

In [31]:
numbs = [1,2,3,4,5,6,7]
oddNum = list(filter(lambda x: x % 2 != 0, numbs)) #filter builtin function

In [74]:
print(oddNum)

[1, 3, 5, 7]

In [1]:
import pandas as pd

In [13]:
customers = pd.DataFrame({
    'CustomerID' : [1,2,3],
    'Name' : ['Ishaq', 'Imran', 'Usman']
})

orders = pd.DataFrame ({
    'OrderID' : [12,13, 14,15],
    'CustomerID' : [1,2,2,3],
    'Amount' : [250,150,200,300]
})

In [14]:
df_inner = pd.merge (customers , orders, on = 'CustomerID', how = 'inner')
print ('inner join\n :', df_inner)

inner join
 :    CustomerID   Name  OrderID  Amount
0           1  Ishaq       12     250
1           2  Imran       13     150
2           2  Imran       14     200
3           3  Usman       15     300

In [15]:
df_left = pd.merge(customers, orders, on= 'CustomerID', how = 'left')
print(df_left)

   CustomerID   Name  OrderID  Amount
0           1  Ishaq       12     250
1           2  Imran       13     150
2           2  Imran       14     200
3           3  Usman       15     300

In [17]:
pdconcat = pd.concat ([ customers, orders])
print(pdconcat)

   CustomerID   Name  OrderID  Amount
0           1  Ishaq      NaN     NaN
1           2  Imran      NaN     NaN
2           3  Usman      NaN     NaN
0           1    NaN     12.0   250.0
1           2    NaN     13.0   150.0
2           2    NaN     14.0   200.0
3           3    NaN     15.0   300.0

In [23]:
df = pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates = ["order_date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [32]:
df["payment_type"] = df["payment_method"].map({
    "Card" : "Digital",
    "Wallet" : "Digital",
    "COD" : "Cash"
})

In [33]:
df["payment_type"].unique()

array(['Digital', 'Cash'], dtype=object)

In [34]:
df[['payment_method', 'payment_type']].head()

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [36]:
df.groupby('payment_type').size()

payment_type
Cash       1774
Digital    3226
dtype: int64

In [38]:
def revenue_category(row):
    if row['revenue'] > 500:
        return 'High'
    elif row['revenue'] >= 200:
        return 'Medium'
    else:
        return 'Low'

df['revenue_category'] = df.apply(revenue_category, axis = 1)
df['revenue_category'].value_counts()

revenue_category
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [39]:
df[['revenue', 'revenue_category']].sample(10)

      revenue revenue_category
3335   206.44           Medium
2107   297.51           Medium
2205  1040.85             High
1423   143.42              Low
455     98.59              Low
2623   805.71             High
4019   529.87             High
2272   668.82             High
3475  1601.12             High
3774  1036.88             High

In [1]:
def add_profit(data):
    data['profit'] = data['revenue'] * 0.20
    return data

def add_net_revenue(data):
    data['net_revenue'] = data['revenue'] - data['profit']
    return data

df = (
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)

)

NameError: name 'df' is not defined

In [41]:
df[['revenue', 'profit', 'net_revenue']].head()

   revenue   profit  net_revenue
0  1883.20  376.640     1506.560
1   304.10   60.820      243.280
2   644.35  128.870      515.480
3  2569.90  513.980     2055.920
4   468.56   93.712      374.848

In [3]:
import pandas as pd
df = pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates = ['order_date'])

In [4]:
df.shape

(5000, 12)

In [10]:
df['revenue'].dtype

dtype('float64')

In [11]:
df['revenue'].isna().sum()

0

In [12]:
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219

In [14]:
df['revenue'].value_counts()

revenue
393.41     2
664.71     2
823.77     2
2879.32    2
701.44     2
          ..
2093.75    1
1370.35    1
853.06     1
211.33     1
1069.90    1
Name: count, Length: 4940, dtype: int64

In [15]:
df[['revenue', 'quantity']].quantile()

revenue     796.65
quantity      4.00
Name: 0.5, dtype: float64

In [16]:
df['revenue'].mean(),df['revenue'].median()

(1021.955148, 796.65)

In [19]:
df['revenue'].skew()

1.0017064603000962

In [22]:
df.groupby('product_category')['revenue'].describe()

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [23]:
df.groupby('product_category')['revenue'].mean()

product_category
Beauty         1059.281992
Clothing       1000.608570
Electronics    1029.768835
Home           1013.502497
Name: revenue, dtype: float64

In [25]:
qa = df['revenue'].quantile(.25)
qb = df['revenue'].quantile(.75)
IQR = qb - qa

qa,qb,IQR

(354.5275, 1515.69, 1161.1625000000001)

In [6]:
import pandas as pd

df = pd.read_csv('ecommerce_sales_analytics_5000.csv', parse_dates = ['order_date'])

q1 = df['revenue'].quantile(0.25)
q3 = df['revenue'].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 *iqr

outliers = df[(df['revenue'] < lower_bound) | (df['revenue'] > upper_bound )]

In [7]:
outliers.shape

(67, 12)

In [11]:
outliers[['revenue', 'product_category']].head()

     revenue product_category
39   3640.56             Home
69   3338.37           Beauty
102  3449.50         Clothing
126  3472.39         Clothing
157  3917.54      Electronics

In [ ]:
df = df[(df['revenue'] >= upper_bou)

In [12]:
from scipy.stats import zscore
df['revenuez'] = zscore(df['revenue'])
outliers = df[df['revenuez'].abs() > 3]

In [13]:
outliers.shape

(26, 13)

In [19]:
q1 = df['revenue'].quantile(0.25)
q3 = df['revenue'].quantile(0.75)

iqr = q3 - q1

lowerbound = q1 - 1.5 * iqr
upperbound = q3 + 1.5 * iqr

outliers = df[(df['revenue'] < lowerbound) | (df['revenue'] > upperbound)]

In [20]:
outliers.shape

(67, 13)

In [22]:
df['rev_z'] = zscore(df['revenue'])
outliers = df[df['rev_z'].abs() > 3]
outliers.shape

(26, 14)